// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: universal.proto

package grpc_

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UniversalUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pattern uint32 `protobuf:"varint,4,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	Data    []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UniversalUserRequest) Reset() {
	*x = UniversalUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniversalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversalUserRequest) ProtoMessage() {}

func (x *UniversalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_universal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversalUserRequest.ProtoReflect.Descriptor instead.
func (*UniversalUserRequest) Descriptor() ([]byte, []int) {
	return file_universal_proto_rawDescGZIP(), []int{0}
}

func (x *UniversalUserRequest) GetPattern() uint32 {
	if x != nil {
		return x.Pattern
	}
	return 0
}

func (x *UniversalUserRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UniversalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State uint32 `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
	Data  []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UniversalResponse) Reset() {
	*x = UniversalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniversalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversalResponse) ProtoMessage() {}

func (x *UniversalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_universal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversalResponse.ProtoReflect.Descriptor instead.
func (*UniversalResponse) Descriptor() ([]byte, []int) {
	return file_universal_proto_rawDescGZIP(), []int{1}
}

func (x *UniversalResponse) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *UniversalResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UniversalResponse_ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State uint32 `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *UniversalResponse_) Reset() {
	*x = UniversalResponse_{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniversalResponse_) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversalResponse_) ProtoMessage() {}

func (x *UniversalResponse_) ProtoReflect() protoreflect.Message {
	mi := &file_universal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversalResponse_.ProtoReflect.Descriptor instead.
func (*UniversalResponse_) Descriptor() ([]byte, []int) {
	return file_universal_proto_rawDescGZIP(), []int{2}
}

func (x *UniversalResponse_) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_universal_proto protoreflect.FileDescriptor

var file_universal_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x44, 0x0a, 0x14, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x50, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x11, 0x55, 0x6e, 0x69, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2a, 0x0a, 0x12, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_universal_proto_rawDescOnce sync.Once
	file_universal_proto_rawDescData = file_universal_proto_rawDesc
)

func file_universal_proto_rawDescGZIP() []byte {
	file_universal_proto_rawDescOnce.Do(func() {
		file_universal_proto_rawDescData = protoimpl.X.CompressGZIP(file_universal_proto_rawDescData)
	})
	return file_universal_proto_rawDescData
}

var file_universal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_universal_proto_goTypes = []interface{}{
	(*UniversalUserRequest)(nil), // 0: UniversalUserRequest
	(*UniversalResponse)(nil),    // 1: UniversalResponse
	(*UniversalResponse_)(nil),   // 2: UniversalResponse_
}
var file_universal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_universal_proto_init() }
func file_universal_proto_init() {
	if File_universal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_universal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniversalUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniversalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniversalResponse_); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_universal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_universal_proto_goTypes,
		DependencyIndexes: file_universal_proto_depIdxs,
		MessageInfos:      file_universal_proto_msgTypes,
	}.Build()
	File_universal_proto = out.File
	file_universal_proto_rawDesc = nil
	file_universal_proto_goTypes = nil
	file_universal_proto_depIdxs = nil
}
